/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resultpackage;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author FrontPage Dreamer
 */
public class settingsPage extends javax.swing.JFrame {

    /**
     * Creates new form settingsPage
     */
    public settingsPage() {
        initComponents();
        showDate();
        showTime();

    }
    Connection con;
    PreparedStatement insert;
    ResultSet rs;

    public void connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/smart_school_management", "root", "");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(settingsPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(settingsPage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    void showDate() {

        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("MM-dd-yyyy");
        dateLabel1.setText(s.format(d));

    }

    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                timeLabel1.setText(s.format(d));
            }
        }).start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        sideBar_attandance = new javax.swing.JLabel();
        sideBar_students1 = new javax.swing.JLabel();
        sideBar_class = new javax.swing.JLabel();
        sideBar_exams = new javax.swing.JLabel();
        sideBar_subjects = new javax.swing.JLabel();
        sideBar_notice = new javax.swing.JLabel();
        sideBar_students = new javax.swing.JLabel();
        sideBar_eca = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        sideBar_settings = new javax.swing.JLabel();
        sideBar_dashboard = new javax.swing.JLabel();
        sideBar_admin = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        timeLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        timeLabel1 = new javax.swing.JLabel();
        dateLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        schoolName = new javax.swing.JLabel();
        schoolAddress = new javax.swing.JLabel();
        schoolLogo = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        pName = new javax.swing.JTextField();
        principleName1 = new javax.swing.JLabel();
        principleName2 = new javax.swing.JLabel();
        pImage = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pMessage = new javax.swing.JTextArea();
        principleNamePreview1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        filepath = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        itemNameField = new javax.swing.JTextField();
        principleName3 = new javax.swing.JLabel();
        principleName4 = new javax.swing.JLabel();
        updateFtBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        itemTextField = new javax.swing.JTextArea();
        item1Radio = new javax.swing.JRadioButton();
        item2Radio = new javax.swing.JRadioButton();
        item3Radio = new javax.swing.JRadioButton();
        closeBtn = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        updateFtBtn1 = new javax.swing.JButton();
        updateSclBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(33, 9, 78));

        jPanel4.setBackground(new java.awt.Color(81, 18, 129));

        jPanel2.setBackground(new java.awt.Color(81, 18, 129));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "School Departments", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 2, 11), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        sideBar_attandance.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        sideBar_attandance.setForeground(new java.awt.Color(255, 153, 51));
        sideBar_attandance.setText("Academics ");

        sideBar_students1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        sideBar_students1.setForeground(new java.awt.Color(255, 153, 51));
        sideBar_students1.setText("Coordinating ");
        sideBar_students1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideBar_students1MouseClicked(evt);
            }
        });

        sideBar_class.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        sideBar_class.setForeground(new java.awt.Color(255, 153, 51));
        sideBar_class.setText("Curriculum ");

        sideBar_exams.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        sideBar_exams.setForeground(new java.awt.Color(255, 153, 51));
        sideBar_exams.setText("ECA ");

        sideBar_subjects.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        sideBar_subjects.setForeground(new java.awt.Color(255, 153, 51));
        sideBar_subjects.setText("Finance ");

        sideBar_notice.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        sideBar_notice.setForeground(new java.awt.Color(255, 153, 51));
        sideBar_notice.setText("Information ");

        sideBar_students.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        sideBar_students.setForeground(new java.awt.Color(255, 153, 51));
        sideBar_students.setText("Recuirtment ");
        sideBar_students.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideBar_studentsMouseClicked(evt);
            }
        });

        sideBar_eca.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        sideBar_eca.setForeground(new java.awt.Color(255, 153, 51));
        sideBar_eca.setText("Fascilities");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sideBar_attandance)
                    .addComponent(sideBar_students1)
                    .addComponent(sideBar_class)
                    .addComponent(sideBar_exams)
                    .addComponent(sideBar_subjects)
                    .addComponent(sideBar_notice)
                    .addComponent(sideBar_students)
                    .addComponent(sideBar_eca))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sideBar_attandance)
                .addGap(18, 18, 18)
                .addComponent(sideBar_students1)
                .addGap(18, 18, 18)
                .addComponent(sideBar_class)
                .addGap(18, 18, 18)
                .addComponent(sideBar_exams)
                .addGap(18, 18, 18)
                .addComponent(sideBar_subjects)
                .addGap(18, 18, 18)
                .addComponent(sideBar_notice)
                .addGap(18, 18, 18)
                .addComponent(sideBar_students)
                .addGap(18, 18, 18)
                .addComponent(sideBar_eca)
                .addContainerGap())
        );

        jPanel19.setBackground(new java.awt.Color(81, 18, 129));
        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Software Management", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 2, 11), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel19.setForeground(new java.awt.Color(255, 255, 255));

        sideBar_settings.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        sideBar_settings.setForeground(new java.awt.Color(255, 153, 51));
        sideBar_settings.setText("Settings");

        sideBar_dashboard.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        sideBar_dashboard.setForeground(new java.awt.Color(255, 153, 51));
        sideBar_dashboard.setText("Dashboard");

        sideBar_admin.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        sideBar_admin.setForeground(new java.awt.Color(255, 153, 51));
        sideBar_admin.setText("Admin");
        sideBar_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideBar_adminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sideBar_settings)
                    .addComponent(sideBar_dashboard)
                    .addComponent(sideBar_admin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sideBar_dashboard)
                .addGap(18, 18, 18)
                .addComponent(sideBar_admin)
                .addGap(18, 18, 18)
                .addComponent(sideBar_settings)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(81, 18, 129));

        timeLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        timeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        timeLabel1.setText("5:17:30 PM");

        dateLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        dateLabel1.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel1.setText("5-27-2021");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(dateLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateLabel)
                            .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(timeLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(dateLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(dateLabel1)
                        .addGap(0, 3, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(33, 9, 78));

        schoolName.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        schoolName.setForeground(new java.awt.Color(255, 255, 255));
        schoolName.setText("Shree Secondary School");

        schoolAddress.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        schoolAddress.setForeground(new java.awt.Color(255, 255, 255));
        schoolAddress.setText("Shivasatakshi 8 Jhiljhile Jhapa");

        schoolLogo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        schoolLogo.setForeground(new java.awt.Color(255, 255, 255));
        schoolLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\FrontPage Dreamer\\Documents\\Icons\\download.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(schoolLogo)
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schoolName)
                    .addComponent(schoolAddress))
                .addContainerGap(599, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schoolLogo)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(schoolName)
                        .addGap(18, 18, 18)
                        .addComponent(schoolAddress)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(33, 9, 78));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pName.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        pName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNameActionPerformed(evt);
            }
        });

        principleName1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        principleName1.setForeground(new java.awt.Color(255, 255, 255));
        principleName1.setText("Name Of Principal");

        principleName2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        principleName2.setForeground(new java.awt.Color(255, 255, 255));
        principleName2.setText("Principal Message");

        pImage.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        pImage.setText("Upload");
        pImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pImageMouseClicked(evt);
            }
        });
        pImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pImageActionPerformed(evt);
            }
        });

        updateBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtnMouseClicked(evt);
            }
        });
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        pMessage.setColumns(20);
        pMessage.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        pMessage.setLineWrap(true);
        pMessage.setRows(5);
        pMessage.setWrapStyleWord(true);
        jScrollPane1.setViewportView(pMessage);

        principleNamePreview1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        principleNamePreview1.setForeground(new java.awt.Color(255, 255, 255));
        principleNamePreview1.setText("Note: Please only select the image having 100 X 100 resolution.");
        principleNamePreview1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        filepath.setEditable(false);
        filepath.setBackground(new java.awt.Color(33, 9, 78));
        filepath.setColumns(10);
        filepath.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        filepath.setForeground(new java.awt.Color(255, 255, 255));
        filepath.setLineWrap(true);
        filepath.setRows(5);
        filepath.setTabSize(1);
        filepath.setWrapStyleWord(true);
        jScrollPane4.setViewportView(filepath);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(principleName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(pImage, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(principleName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(pName, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(principleNamePreview1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(principleNamePreview1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(principleName1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(principleName2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)))
                .addGap(4, 4, 4)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(pImage)))
                .addGap(18, 18, 18)
                .addComponent(updateBtn)
                .addGap(46, 46, 46))
        );

        jPanel8.setBackground(new java.awt.Color(33, 9, 78));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        itemNameField.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        itemNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNameFieldActionPerformed(evt);
            }
        });

        principleName3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        principleName3.setForeground(new java.awt.Color(255, 255, 255));
        principleName3.setText("Item Name");

        principleName4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        principleName4.setForeground(new java.awt.Color(255, 255, 255));
        principleName4.setText("Item Text");

        updateFtBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        updateFtBtn.setText("Update Featured Item");
        updateFtBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateFtBtnMouseClicked(evt);
            }
        });
        updateFtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFtBtnActionPerformed(evt);
            }
        });

        itemTextField.setColumns(20);
        itemTextField.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        itemTextField.setLineWrap(true);
        itemTextField.setRows(5);
        itemTextField.setWrapStyleWord(true);
        jScrollPane3.setViewportView(itemTextField);

        item1Radio.setBackground(new java.awt.Color(33, 9, 78));
        buttonGroup1.add(item1Radio);
        item1Radio.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        item1Radio.setForeground(new java.awt.Color(255, 255, 255));
        item1Radio.setText("Item1");
        item1Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item1RadioActionPerformed(evt);
            }
        });

        item2Radio.setBackground(new java.awt.Color(33, 9, 78));
        buttonGroup1.add(item2Radio);
        item2Radio.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        item2Radio.setForeground(new java.awt.Color(255, 255, 255));
        item2Radio.setText("Item2");
        item2Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item2RadioActionPerformed(evt);
            }
        });

        item3Radio.setBackground(new java.awt.Color(33, 9, 78));
        buttonGroup1.add(item3Radio);
        item3Radio.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        item3Radio.setForeground(new java.awt.Color(255, 255, 255));
        item3Radio.setText("Item3");
        item3Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item3RadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(principleName4)
                    .addComponent(principleName3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(item1Radio)
                        .addGap(42, 42, 42)
                        .addComponent(item2Radio)
                        .addGap(29, 29, 29)
                        .addComponent(item3Radio)))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateFtBtn)
                .addGap(76, 76, 76))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(principleName3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item3Radio)
                    .addComponent(item2Radio)
                    .addComponent(item1Radio))
                .addGap(38, 38, 38)
                .addComponent(updateFtBtn)
                .addGap(79, 79, 79))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(principleName4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resultpackage/close-icon.png"))); // NOI18N
        closeBtn.setToolTipText("Close");
        closeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });

        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resultpackage/minimize-icon.png"))); // NOI18N
        minimizeBtn.setToolTipText("Minimize");
        minimizeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(33, 9, 78));
        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        updateFtBtn1.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        updateFtBtn1.setText("Update Contact Info");
        updateFtBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateFtBtn1MouseClicked(evt);
            }
        });
        updateFtBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFtBtn1ActionPerformed(evt);
            }
        });

        updateSclBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        updateSclBtn.setText("Change School Info");
        updateSclBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateSclBtnMouseClicked(evt);
            }
        });
        updateSclBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSclBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateFtBtn1)
                    .addComponent(updateSclBtn))
                .addGap(24, 24, 24))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(updateSclBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateFtBtn1)
                .addGap(158, 158, 158))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minimizeBtn)
                        .addGap(18, 18, 18)
                        .addComponent(closeBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(closeBtn)
                            .addComponent(minimizeBtn)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void sideBar_students1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideBar_students1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sideBar_students1MouseClicked

    private void sideBar_studentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideBar_studentsMouseClicked


    }//GEN-LAST:event_sideBar_studentsMouseClicked

    private void sideBar_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideBar_adminMouseClicked


    }//GEN-LAST:event_sideBar_adminMouseClicked

    private void pNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pNameActionPerformed

    private void pImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pImageActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        if (pName.getText().trim().isEmpty() || pMessage.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Input fields cannot be empty.", "Message", JOptionPane.OK_OPTION);
        } else {
            //show preview
            String nameShow = pName.getText();
           
            String messageShow = pMessage.getText();
           
            

            //Add details in database
            String name = pName.getText();
            String message = pMessage.getText();

            try {
                connect();
                insert = con.prepareStatement("insert into principle_information(name,message,image)values(?,?,?)");
                insert.setString(1, name);
                insert.setString(2, message);
                insert.setBytes(3, photo);
                insert.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data is added successfully!");
            } catch (SQLException ex) {
                Logger.getLogger(settingsPage.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        pName.setText(" ");
        pMessage.setText(" ");
        filepath.setText(" ");
        pName.requestFocus(true);


    }//GEN-LAST:event_updateBtnActionPerformed

    private void updateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseClicked


    }//GEN-LAST:event_updateBtnMouseClicked

    private void pImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pImageMouseClicked

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        schoolLogo.setIcon(new ImageIcon(f.toString()));
        String filename = f.getAbsolutePath();
        filepath.setText(filename);
        try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int readNum; (readNum = fis.read(buf)) != -1;) {
                bos.write(buf, 0, readNum);
            }

            photo = bos.toByteArray();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_pImageMouseClicked

    private void itemNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameFieldActionPerformed

    private void updateFtBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateFtBtnMouseClicked


    }//GEN-LAST:event_updateFtBtnMouseClicked

    private void updateFtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFtBtnActionPerformed

        if (itemNameField.getText().trim().isEmpty() || itemTextField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Input fields cannot be empty.", "Message", JOptionPane.OK_OPTION);
        } else {
            String itemNameShow = itemNameField.getText();
            String itemMsgShow = itemTextField.getText();

            //show preview
          
           

            if (itemNo == "Item 1") {
                try {

                    //Add details in database
                    connect();
                    insert = con.prepareStatement("insert into featured_item1(itemName,itemText)values(?,?)");
                    insert.setString(1, itemNameShow);
                    insert.setString(2, itemMsgShow);
                    insert.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Data is added successfully!");

                } catch (SQLException ex) {
                    Logger.getLogger(settingsPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (itemNo == "Item 2") {
                try {
                    //Add details in database

                    connect();
                    insert = con.prepareStatement("insert into featured_item2(itemName,itemText)values(?,?)");
                    insert.setString(1, itemNameShow);
                    insert.setString(2, itemMsgShow);
                    insert.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Data is added successfully!");

                } catch (SQLException ex) {
                    Logger.getLogger(settingsPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {
                    //Add details in database

                    connect();
                    insert = con.prepareStatement("insert into featured_item3(itemName,itemText)values(?,?)");
                    insert.setString(1, itemNameShow);
                    insert.setString(2, itemMsgShow);
                    insert.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Data is added successfully!");

                } catch (SQLException ex) {
                    Logger.getLogger(settingsPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }


    }//GEN-LAST:event_updateFtBtnActionPerformed

    private void updateSclBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateSclBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_updateSclBtnMouseClicked

    private void updateSclBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSclBtnActionPerformed
        
        schoolInfoUpdate siu=new schoolInfoUpdate();
        this.hide();
        siu.setVisible(true);
      

    }//GEN-LAST:event_updateSclBtnActionPerformed

    private void updateFtBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateFtBtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_updateFtBtn1MouseClicked

    private void updateFtBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFtBtn1ActionPerformed

        socialMediaInfo smi=new socialMediaInfo();
        this.hide();
        smi.setVisible(true);


    }//GEN-LAST:event_updateFtBtn1ActionPerformed

    private void item2RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item2RadioActionPerformed
        itemNo = "Item 2";
    }//GEN-LAST:event_item2RadioActionPerformed

    private void item1RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item1RadioActionPerformed

        itemNo = "Item 1";
    }//GEN-LAST:event_item1RadioActionPerformed

    private void item3RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item3RadioActionPerformed
        itemNo = "Item 3";
    }//GEN-LAST:event_item3RadioActionPerformed

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked

        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_closeBtnMouseClicked

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked

        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(settingsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(settingsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(settingsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(settingsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new settingsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel dateLabel1;
    private javax.swing.JTextArea filepath;
    private javax.swing.JRadioButton item1Radio;
    private javax.swing.JRadioButton item2Radio;
    private javax.swing.JRadioButton item3Radio;
    private javax.swing.JTextField itemNameField;
    private javax.swing.JTextArea itemTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel minimizeBtn;
    private javax.swing.JButton pImage;
    private javax.swing.JTextArea pMessage;
    private javax.swing.JTextField pName;
    private javax.swing.JLabel principleName1;
    private javax.swing.JLabel principleName2;
    private javax.swing.JLabel principleName3;
    private javax.swing.JLabel principleName4;
    private javax.swing.JLabel principleNamePreview1;
    private javax.swing.JLabel schoolAddress;
    private javax.swing.JLabel schoolLogo;
    private javax.swing.JLabel schoolName;
    private javax.swing.JLabel sideBar_admin;
    private javax.swing.JLabel sideBar_attandance;
    private javax.swing.JLabel sideBar_class;
    private javax.swing.JLabel sideBar_dashboard;
    private javax.swing.JLabel sideBar_eca;
    private javax.swing.JLabel sideBar_exams;
    private javax.swing.JLabel sideBar_notice;
    private javax.swing.JLabel sideBar_settings;
    private javax.swing.JLabel sideBar_students;
    private javax.swing.JLabel sideBar_students1;
    private javax.swing.JLabel sideBar_subjects;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel timeLabel1;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton updateFtBtn;
    private javax.swing.JButton updateFtBtn1;
    private javax.swing.JButton updateSclBtn;
    // End of variables declaration//GEN-END:variables
private String itemNo;
    byte[] photo = null;
}
