/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resultpackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author FrontPage Dreamer
 */
public class socialMediaInfo extends javax.swing.JFrame {

    /**
     * Creates new form socialMediaInfo
     */
    public socialMediaInfo() {
        initComponents();
        show();
    }
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    public void show() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/smart_school_management", "root", "");
            String fetch_row="select facebook from socialmedia_info where id=1";
            
           // pst = con.prepareStatement("select * from socialmedia_info");
           pst=con.prepareStatement(fetch_row);
            rs=pst.executeQuery();
            while(rs.next()){
                String facebookdata=rs.getString(1);
               fb.setText(facebookdata);  
            }
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(socialMediaInfo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(socialMediaInfo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        principleName6 = new javax.swing.JLabel();
        principleName7 = new javax.swing.JLabel();
        principleName8 = new javax.swing.JLabel();
        principleName9 = new javax.swing.JLabel();
        principleName10 = new javax.swing.JLabel();
        principleName11 = new javax.swing.JLabel();
        principleNamePreview3 = new javax.swing.JLabel();
        fb = new javax.swing.JTextField();
        b2Name = new javax.swing.JTextField();
        eId = new javax.swing.JTextField();
        wsite = new javax.swing.JTextField();
        b2Url = new javax.swing.JTextField();
        ph1 = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        ph2 = new javax.swing.JTextField();
        principleName12 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(33, 9, 78));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jPanel2.setBackground(new java.awt.Color(33, 9, 78));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        principleName6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        principleName6.setForeground(new java.awt.Color(255, 255, 255));
        principleName6.setText("Facebook");

        principleName7.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        principleName7.setForeground(new java.awt.Color(255, 255, 255));
        principleName7.setText("Banner 2 Name");

        principleName8.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        principleName8.setForeground(new java.awt.Color(255, 255, 255));
        principleName8.setText("Website");

        principleName9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        principleName9.setForeground(new java.awt.Color(255, 255, 255));
        principleName9.setText("Banner 2 URL");

        principleName10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        principleName10.setForeground(new java.awt.Color(255, 255, 255));
        principleName10.setText("Email ID");

        principleName11.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        principleName11.setForeground(new java.awt.Color(255, 255, 255));
        principleName11.setText("Phone Number 1");

        principleNamePreview3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        principleNamePreview3.setForeground(new java.awt.Color(255, 255, 255));
        principleNamePreview3.setText("Please enter the valid social platforms URL");
        principleNamePreview3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        fb.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        b2Name.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        eId.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        wsite.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        b2Url.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        ph1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        updateBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        ph2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        principleName12.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        principleName12.setForeground(new java.awt.Color(255, 255, 255));
        principleName12.setText("Phone Number 2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(principleName7)
                                .addGap(28, 28, 28))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(principleName12)
                                        .addComponent(principleName11))
                                    .addComponent(principleName10)
                                    .addComponent(principleName8)
                                    .addComponent(principleName9)
                                    .addComponent(principleName6))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ph1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eId, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wsite, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2Url, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2Name, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ph2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fb, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(principleNamePreview3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(updateBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(principleNamePreview3)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(principleName6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b2Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(principleName7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b2Url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(principleName9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(principleName8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(principleName10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ph1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(principleName11, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ph2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(principleName12, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(updateBtn)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        backBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        if (fb.getText().trim().isEmpty() || b2Name.getText().trim().isEmpty() || b2Url.getText().trim().isEmpty() || wsite.getText().trim().isEmpty() || eId.getText().trim().isEmpty()
                || ph1.getText().trim().isEmpty() || ph2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Input fields cannot be empty. All informations are required.", "Message", JOptionPane.OK_OPTION);
        } else {
            String fbUrl = fb.getText();
            String b2name = b2Name.getText();
            String b2url = b2Url.getText();
            String website = wsite.getText();
            String email = eId.getText();
            String phone1 = ph1.getText();
            String phone2 = ph2.getText();

            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/smart_school_management", "root", "");
                pst = con.prepareStatement("update socialmedia_info set facebook= ?,b2Name= ?, b2Url= ?, website= ?, email= ?, phone1= ?, phone2= ? where id= 1");
                //pst = con.prepareStatement("insert into socialmedia_info (facebook,b2Name,b2Url,website,email,phone1,phone2) values(?,?,?,?,?,?,?)");
                pst.setString(1, fbUrl);
                pst.setString(2, b2name);
                pst.setString(3, b2url);
                pst.setString(4, website);
                pst.setString(5, email);
                pst.setString(6, phone1);
                pst.setString(7, phone2);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Informations are successfully updated.");
                fb.setText(" ");
                b2Name.setText(" ");
                b2Url.setText(" ");
                wsite.setText(" ");
                eId.setText(" ");
                ph1.setText(" ");
                ph2.setText(" ");

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(socialMediaInfo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(socialMediaInfo.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_updateBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        settingsPage sp = new settingsPage();
        this.hide();
        sp.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(socialMediaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(socialMediaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(socialMediaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(socialMediaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new socialMediaInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b2Name;
    private javax.swing.JTextField b2Url;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField eId;
    private javax.swing.JTextField fb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField ph1;
    private javax.swing.JTextField ph2;
    private javax.swing.JLabel principleName10;
    private javax.swing.JLabel principleName11;
    private javax.swing.JLabel principleName12;
    private javax.swing.JLabel principleName6;
    private javax.swing.JLabel principleName7;
    private javax.swing.JLabel principleName8;
    private javax.swing.JLabel principleName9;
    private javax.swing.JLabel principleNamePreview3;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField wsite;
    // End of variables declaration//GEN-END:variables
}
